export type SessionStatus =
  | 'IDLE'
  | 'PRE_QUIZ'
  | 'PRESENTING'
  | 'POST_QA'
  | 'REPORT'
  | 'DONE';

export interface QuizItem {
  id: number;
  question: string;
  key_points: string[];
}

/** Per-question grading result for the pre-quiz */
export interface PreQuizQuestionGrade {
  id: number;
  score: number;
  feedback: string;
}

/** Minimum score to display as "pass" in the UI */
export const PRE_QUIZ_PASS_SCORE = 70;

export interface WpmEntry {
  timestamp: number;
  wpm: number;
}

export interface OffTopicEntry {
  timestamp: number;
  excerpt: string;
  reason: string;
}

export interface GazeEntry {
  timestamp: number;
  is_gazing: boolean;
  /** 시선이 카메라 기준으로 향한 방향 */
  direction: 'center' | 'left' | 'right';
}

export interface PostureEntry {
  timestamp: number;
  angle: number;
  is_ok: boolean;
}

export interface GestureEntry {
  timestamp: number;
  type: 'excess' | 'lack';
}

export interface DynamismEntry {
  timestamp: number;
  level: 'stiff' | 'natural' | 'restless';
}

export interface QaExchange {
  turn: number;
  question: string;
  answer: string;
  score?: number;
}

// ── Script RAG types ────────────────────────────────────────────────────────

/** Processing state of the script embedding pipeline */
export type ScriptEmbeddingStatus = 'idle' | 'processing' | 'ready' | 'error';

/** Style profile generated by analyzeScriptStyle() */
export interface ScriptStyleAnalysis {
  tone: string;
  complexity: string;
  keyPhrases: string[];
  estimatedMinutes: number;
  deliverySuggestions: string[];
}

// ── SessionContext ──────────────────────────────────────────────────────────

export interface SessionContext {
  session_id: string;
  user_id: string;
  status: SessionStatus;
  started_at: string;
  ended_at?: string;

  /** Selected topic keys `categoryId:subId` (multi). Includes `other:custom` when using free-text. */
  presentation_topic_keys: string[];
  /** Free text when “기타” is used or the presenter adds extra context. */
  presentation_topic_custom: string;

  material: {
    raw_text: string;
    summary: string;
    keywords: string[];
    quiz: QuizItem[];
    pre_quiz_score: number;
    /** Per-question scores and feedback (after full submission grading) */
    pre_quiz_grades: PreQuizQuestionGrade[];
    weak_areas: string[];
    /** Optional presentation script text (uploaded or typed by user) */
    script_text: string;
    /** Embedding processing state */
    script_embedding_status: ScriptEmbeddingStatus;
    /** Chunk count after embedding (0 = not yet processed) */
    script_chunk_count: number;
    /** AI style analysis of the script */
    script_style?: ScriptStyleAnalysis;
    /** 0–1 coverage ratio filled by reportAgent */
    script_coverage?: number;
  };

  speech_coaching: {
    wpm_log: WpmEntry[];
    filler_count: number;
    filler_timestamps: number[];
    off_topic_log: OffTopicEntry[];
    ambiguous_count: number;
    total_duration_sec: number;
    transcript_log: TranscriptEntry[];
  };

  nonverbal_coaching: {
    gaze_rate: number;
    gaze_log: GazeEntry[];
    posture_log: PostureEntry[];
    gesture_log: GestureEntry[];
    dynamism_log: DynamismEntry[];
  };

  /** True when the user chose to skip the practice Q&A and generate the report from speech/nonverbal only. */
  qa_skipped?: boolean;

  qa: {
    exchanges: QaExchange[];
    /** 이 세션에서 진행할 Q&A 질문 수(3–5), 세션 생성 시 무작위 고정 */
    planned_rounds: number;
    final_score: number;
    best_answer_turn: number;
    worst_answer_turn: number;
  };

  report: {
    composite_score: number;
    speech_score: number;
    nonverbal_score: number;
    qa_score: number;
    strengths: string[];
    improvements: ActionableFeedback[] | string[];
    generated_at: string;
    /** Present when a coach persona was selected and the narrative model returned this block. */
    persona_style_coaching?: PersonaStyleCoaching | null;
  };
}

export interface TimeMarker {
  time: string;
  event: string;
}

export interface ActionableFeedback {
  label: string;
  situation: string;
  stop_doing: string;
  start_doing: string;
  expected_impact: string;
  time_markers?: TimeMarker[];
}

/** Persona-benchmark delivery & rhetoric section (report only; optional for older sessions). */
export interface PersonaPhraseRewrite {
  /** 실제 발화·전사에서 인용한 한 덩어리 */
  from_session: string;
  /** 선택한 코치 톤으로 다시 말한 예시(말하는 방식 위주) */
  persona_aligned_example: string;
  /** 선택: 왜 이렇게 바꾸는지 한 줄(호흡·띄어읽기·근거 제시 방식 등) */
  why?: string;
}

export interface PersonaStyleCoaching {
  style_alignment: string;
  delivery_practices: string[];
  phrase_rewrites?: PersonaPhraseRewrite[];
}

export type AgentId =
  | 'ORCHESTRATOR'
  | 'MATERIAL'
  | 'SPEECH_RULE'
  | 'SPEECH_SEMANTIC'
  | 'NONVERBAL'
  | 'QA'
  | 'REPORT';

export interface TranscriptEntry {
  text: string;
  timestamp: number;
}

export interface FillerEntry {
  word: string;
  timestamp: number;
}

export type FeedbackLevel = 'CRITICAL' | 'WARN' | 'INFO';

export type FeedbackSource = 'SPEECH_RULE' | 'SPEECH_SEMANTIC' | 'NONVERBAL';

export interface FeedbackItem {
  id: string;
  level: FeedbackLevel;
  msg: string;
  source: FeedbackSource;
  cooldown: number;
  createdAt: number;
  silent?: boolean;
}

export interface ReportScores {
  compositeScore: number;
  speechScore: number;
  nonverbalScore: number;
  qaScore: number;
}
